
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.ScrolledWindow scrolledwindow1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Expander expander1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.Label GtkLabel3;
	private global::Gtk.Expander expander2;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Button button4;
	private global::Gtk.Label GtkLabel5;
	private global::Gtk.Expander expander3;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Button button5;
	private global::Gtk.Label GtkLabel7;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Expander expander4;
	private global::Gtk.Label GtkLabel8;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 212;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.expander1 = new global::Gtk.Expander (null);
		this.expander1.CanFocus = true;
		this.expander1.Name = "expander1";
		this.expander1.Expanded = true;
		// Container child expander1.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Xalign = 0.15F;
		// Container child button1.Gtk.Container+ContainerChild
		global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.15F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w3 = new global::Gtk.HBox ();
		w3.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w4 = new global::Gtk.Image ();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		w3.Add (w4);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.LabelProp = global::Mono.Unix.Catalog.GetString ("Begin");
		w6.UseUnderline = true;
		w3.Add (w6);
		w2.Add (w3);
		this.button1.Add (w2);
		this.vbox2.Add (this.button1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Xalign = 0.15F;
		// Container child button2.Gtk.Container+ContainerChild
		global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.15F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w12 = new global::Gtk.HBox ();
		w12.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w13 = new global::Gtk.Image ();
		w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		w12.Add (w13);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w15 = new global::Gtk.Label ();
		w15.LabelProp = global::Mono.Unix.Catalog.GetString ("If");
		w15.UseUnderline = true;
		w12.Add (w15);
		w11.Add (w12);
		this.button2.Add (w11);
		this.vbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Xalign = 0.15F;
		// Container child button3.Gtk.Container+ContainerChild
		global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.15F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w21 = new global::Gtk.HBox ();
		w21.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w22 = new global::Gtk.Image ();
		w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		w21.Add (w22);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w24 = new global::Gtk.Label ();
		w24.LabelProp = global::Mono.Unix.Catalog.GetString ("If Else");
		w24.UseUnderline = true;
		w21.Add (w24);
		w20.Add (w21);
		this.button3.Add (w20);
		this.vbox2.Add (this.button3);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button3]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.expander1.Add (this.vbox2);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Control");
		this.GtkLabel3.UseUnderline = true;
		this.expander1.LabelWidget = this.GtkLabel3;
		this.vbox1.Add (this.expander1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander1]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.expander2 = new global::Gtk.Expander (null);
		this.expander2.CanFocus = true;
		this.expander2.Name = "expander2";
		this.expander2.Expanded = true;
		// Container child expander2.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Xalign = 0.15F;
		// Container child button4.Gtk.Container+ContainerChild
		global::Gtk.Alignment w31 = new global::Gtk.Alignment (0.15F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w32 = new global::Gtk.HBox ();
		w32.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w33 = new global::Gtk.Image ();
		w33.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		w32.Add (w33);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w35 = new global::Gtk.Label ();
		w35.LabelProp = global::Mono.Unix.Catalog.GetString ("Let");
		w35.UseUnderline = true;
		w32.Add (w35);
		w31.Add (w32);
		this.button4.Add (w31);
		this.vbox3.Add (this.button4);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button4]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		this.expander2.Add (this.vbox3);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("Variables");
		this.GtkLabel5.UseUnderline = true;
		this.expander2.LabelWidget = this.GtkLabel5;
		this.vbox1.Add (this.expander2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander2]));
		w41.Position = 1;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.expander3 = new global::Gtk.Expander (null);
		this.expander3.CanFocus = true;
		this.expander3.Name = "expander3";
		this.expander3.Expanded = true;
		// Container child expander3.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Xalign = 0.15F;
		// Container child button5.Gtk.Container+ContainerChild
		global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.15F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w43 = new global::Gtk.HBox ();
		w43.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w44 = new global::Gtk.Image ();
		w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		w43.Add (w44);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w46 = new global::Gtk.Label ();
		w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Print");
		w46.UseUnderline = true;
		w43.Add (w46);
		w42.Add (w43);
		this.button5.Add (w42);
		this.vbox4.Add (this.button5);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button5]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		this.expander3.Add (this.vbox4);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("Input/Output");
		this.GtkLabel7.UseUnderline = true;
		this.expander3.LabelWidget = this.GtkLabel7;
		this.vbox1.Add (this.expander3);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander3]));
		w52.Position = 2;
		w52.Expand = false;
		w52.Fill = false;
		w1.Add (this.vbox1);
		this.scrolledwindow1.Add (w1);
		this.hpaned1.Add (this.scrolledwindow1);
		global::Gtk.Paned.PanedChild w55 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.scrolledwindow1]));
		w55.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.expander4 = new global::Gtk.Expander (null);
		this.expander4.CanFocus = true;
		this.expander4.Name = "expander4";
		this.expander4.Expanded = true;
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("Begin");
		this.GtkLabel8.UseUnderline = true;
		this.expander4.LabelWidget = this.GtkLabel8;
		this.vbox5.Add (this.expander4);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.expander4]));
		w56.Position = 0;
		this.hpaned1.Add (this.vbox5);
		this.Add (this.hpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 570;
		this.DefaultHeight = 421;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.DragBegin += new global::Gtk.DragBeginHandler (this.OnButton1DragBegin);
		this.button1.DragDataGet += new global::Gtk.DragDataGetHandler (this.OnButton1DragDataGet);
		this.button1.DragDataReceived += new global::Gtk.DragDataReceivedHandler (this.OnButton1DragDataReceived);
		this.button1.DragDrop += new global::Gtk.DragDropHandler (this.OnButton1DragDrop);
		this.button1.DragEnd += new global::Gtk.DragEndHandler (this.OnButton1DragEnd);
		this.button1.DragLeave += new global::Gtk.DragLeaveHandler (this.OnButton1DragLeave);
		this.button1.DragMotion += new global::Gtk.DragMotionHandler (this.OnButton1DragMotion);
		this.button1.DragDataDelete += new global::Gtk.DragDataDeleteHandler (this.OnButton1DragDataDelete);
	}
}
