import Myro
Myro.init("/dev/rfcomm1")

pic = Myro.takePicture()
Myro.show(pic)

Myro.robot.backward(1, 1)
Myro.robot.forward(1, 1)
Myro.robot.beep(1, 440)
Myro.robot.beep(1, 440, 880)
Myro.robot.forward(.5, 2)
Myro.robot.backward(.5, 2)
print Myro.robot.get("all")
print Myro.robot.getAll()
print Myro.robot.getBattery()
print Myro.robot.getBlob()
# print Myro.robot.getBright()
print Myro.robot.getConfig()
print Myro.robot.getData()
print Myro.robot.getIR()
print Myro.robot.getIRMessage()
print Myro.robot.getInfo()
print Myro.robot.getLight()
print Myro.robot.getLine()
print Myro.robot.getName()
# print Myro.robot.getObstacle()
print Myro.robot.getPassword()
print Myro.robot.getStall()
Myro.robot.motors(.5, .5)
Myro.robot.move(1, 1)
Myro.robot.move(-1, -1)
Myro.robot.reboot()
Myro.robot.rotate(.5, 1)
Myro.robot.rotate(-.5, 1)
#Myro.robot.sendIRMessage
#Myro.robot.setCommunicate
#Myro.robot.setData(0, 0)
print Myro.robot.getData()
#Myro.robot.setData(0, 128)
#Myro.robot.setEchoMode
#Myro.robot.setForwardness
#Myro.robot.setIRPower
Myro.robot.setLED("front", 1)
Myro.robot.setLEDBack(1)
Myro.robot.setLEDBack(0)
Myro.robot.setLEDFront(1)
Myro.robot.setLEDFront(0)
Myro.robot.setName("Hello")
print Myro.robot.getName()
Myro.robot.setName("Scribby")
print Myro.robot.getName()
Myro.robot.setPassword("password")
#Myro.robot.setWhiteBalance
Myro.robot.setup()
Myro.robot.stop()
p = Myro.robot.takePicture()
Myro.robot.translate(.5, 1)
Myro.robot.translate(-.5, 1)
Myro.robot.turnLeft(1, .25)
Myro.robot.turnLeft(0.5, .25)
Myro.robot.turnRight(0.5, .25)
Myro.robot.turnRight(1, .25)
