#!/bin/bash
export LD_LIBRARY_PATH=/Library/Frameworks/Mono.framework/Libraries/:$LD_LIBRARY_PATH
if [ -L $0 ] ; then
    DIR=$(dirname $(readlink -f "$0")) ;
else
    DIR=$(dirname "$0") ;
fi ;
cd $DIR
/usr/bin/env mono $MONO_OPTIONS bin/pyjama.exe "$@"
