#!/bin/sh
if [ "$1" = "--debug" ]; then
        MONO_OPTIONS="--debug"
        shift
fi

/usr/bin/env mono $MONO_OPTIONS bin/ipy.exe -X:FullFrames -X:ShowClrExceptions -X:Debug -X:ExceptionDetail src/pyjama.py "$@"
