# This Python program was automatically generated by Calico Jigsaw
# http://calicoproject.org

#see the spritesSimpleDemo.jig example for detailed comments

import Common
import Sprites

Sprites.init()

Sprites.setVoice("English-US Female")
Sprites.speak("Hello World!  Welcome to the Sprites module.", 1)
for _ in range(6):
    Sprites.forward(10)                                                 #appears to be the same as forward(60) when tracer slider is all the way to the left
Sprites.glideTo(170, 220, 2)
Sprites.changeCostume("pinkHair")

Sprites.makeSprite("Cally")
Sprites.selectSprite("Cally")
Sprites.changeCostume("greenHair")
Sprites.rotate(-30)
Sprites.glideForward(180, 2)
Sprites.rotateTo(0)

Sprites.selectSprite("Sprite1")
Sprites.scale(1.5)

Sprites.selectSprite("Cally")
Sprites.scale(1.7)

Sprites.changeBackground("sun")
