
CalicoDinah.dll: AssemblyInfo.cs CalicoDinah.cs Dinah.cs Engine.cs Main.cs \
	MainWindow.cs Program.cs Statement.cs StatementFactory.cs
	dmcs -lib:../../bin *.cs -r:Calico.exe -pkg:gtk-sharp-2.0 -r:Mono.Posix -target:library -out:CalicoDinah.dll
