
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action newAction1;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action yesAction;

	private global::Gtk.Action stopAction;

	private global::Gtk.Action goForwardAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action openAction1;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action copyAction;

	private global::Gtk.Action pasteAction;

	private global::Gtk.Action cutAction;

	private global::Gtk.Action undoAction;

	private global::Gtk.Action redoAction;

	private global::Gtk.Action selectAllAction;

	private global::Gtk.Action indentAction;

	private global::Gtk.Action unindentAction;

	private global::Gtk.Action CommentRegionAction;

	private global::Gtk.Action UncommentRegionAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action helpAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action ShellAction;

	private global::Gtk.Action Action;

	private global::Gtk.Action LanguageAction;

	private global::Gtk.RadioAction PythonAction;

	private global::Gtk.RadioAction RubyAction;

	private global::Gtk.RadioAction SchemeAction;

	private global::Gtk.RadioAction JigsawAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.VPaned vpaned2;

	private global::Gtk.Notebook notebook_docs;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button button4;

	private global::Gtk.Button button3;

	private global::Gtk.Button button2;

	private global::Gtk.Image image69;

	private global::Gtk.Label label2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label prompt;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button button10;

	private global::Gtk.Button button11;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Label label1;

	private global::Gtk.Notebook notebook_tools;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.Label label3;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", null, null, "gtk-new");
		this.newAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.newAction1, null);
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.yesAction = new global::Gtk.Action ("yesAction", null, null, "gtk-yes");
		this.yesAction.Sensitive = false;
		w1.Add (this.yesAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", null, null, "gtk-stop");
		this.stopAction.Sensitive = false;
		w1.Add (this.stopAction, null);
		this.goForwardAction = new global::Gtk.Action ("goForwardAction", null, null, "gtk-go-forward");
		this.goForwardAction.Sensitive = false;
		w1.Add (this.goForwardAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction1, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
		w1.Add (this.saveAsAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.copyAction = new global::Gtk.Action ("copyAction", global::Mono.Unix.Catalog.GetString ("_Copy"), null, "gtk-copy");
		this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Copy");
		w1.Add (this.copyAction, null);
		this.pasteAction = new global::Gtk.Action ("pasteAction", global::Mono.Unix.Catalog.GetString ("_Paste"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Paste");
		w1.Add (this.pasteAction, null);
		this.cutAction = new global::Gtk.Action ("cutAction", global::Mono.Unix.Catalog.GetString ("Cu_t"), null, "gtk-cut");
		this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cu_t");
		w1.Add (this.cutAction, null);
		this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("_Undo"), null, "gtk-undo");
		this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Undo");
		w1.Add (this.undoAction, "<Control><Mod2>z");
		this.redoAction = new global::Gtk.Action ("redoAction", global::Mono.Unix.Catalog.GetString ("_Redo"), null, "gtk-redo");
		this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Redo");
		w1.Add (this.redoAction, "<Control><Shift>z");
		this.selectAllAction = new global::Gtk.Action ("selectAllAction", global::Mono.Unix.Catalog.GetString ("Select _All"), null, "gtk-select-all");
		this.selectAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select _All");
		w1.Add (this.selectAllAction, "<Control><Mod2>a");
		this.indentAction = new global::Gtk.Action ("indentAction", global::Mono.Unix.Catalog.GetString ("Indent Region"), null, "gtk-indent");
		this.indentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Indent Region");
		w1.Add (this.indentAction, null);
		this.unindentAction = new global::Gtk.Action ("unindentAction", global::Mono.Unix.Catalog.GetString ("Unindent Region"), null, "gtk-unindent");
		this.unindentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Unindent Region");
		w1.Add (this.unindentAction, null);
		this.CommentRegionAction = new global::Gtk.Action ("CommentRegionAction", global::Mono.Unix.Catalog.GetString ("Comment Region"), null, null);
		this.CommentRegionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Comment Region");
		w1.Add (this.CommentRegionAction, null);
		this.UncommentRegionAction = new global::Gtk.Action ("UncommentRegionAction", global::Mono.Unix.Catalog.GetString ("Uncomment Region"), null, null);
		this.UncommentRegionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Uncomment Region");
		w1.Add (this.UncommentRegionAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.helpAction = new global::Gtk.Action ("helpAction", null, null, "gtk-help");
		w1.Add (this.helpAction, null);
		this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-about");
		this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
		w1.Add (this.aboutAction, null);
		this.ShellAction = new global::Gtk.Action ("ShellAction", global::Mono.Unix.Catalog.GetString ("Shell"), null, null);
		this.ShellAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Shell");
		w1.Add (this.ShellAction, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("--"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("--");
		w1.Add (this.Action, null);
		this.LanguageAction = new global::Gtk.Action ("LanguageAction", global::Mono.Unix.Catalog.GetString ("Language"), null, null);
		this.LanguageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Language");
		w1.Add (this.LanguageAction, null);
		this.PythonAction = new global::Gtk.RadioAction ("PythonAction", global::Mono.Unix.Catalog.GetString ("Python"), null, null, 0);
		this.PythonAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.PythonAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Python");
		w1.Add (this.PythonAction, null);
		this.RubyAction = new global::Gtk.RadioAction ("RubyAction", global::Mono.Unix.Catalog.GetString ("Ruby"), null, null, 0);
		this.RubyAction.Group = this.PythonAction.Group;
		this.RubyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ruby");
		w1.Add (this.RubyAction, null);
		this.SchemeAction = new global::Gtk.RadioAction ("SchemeAction", global::Mono.Unix.Catalog.GetString ("Scheme"), null, null, 0);
		this.SchemeAction.Group = this.RubyAction.Group;
		this.SchemeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Scheme");
		w1.Add (this.SchemeAction, null);
		this.JigsawAction = new global::Gtk.RadioAction ("JigsawAction", global::Mono.Unix.Catalog.GetString ("Jigsaw"), null, null, 0);
		this.JigsawAction.Group = this.RubyAction.Group;
		this.JigsawAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Jigsaw");
		w1.Add (this.JigsawAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Calico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='newAction1' action='newAction1'/><menuitem name='openAction1' action='openAction1'/><separator/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='copyAction' action='copyAction'/><menuitem name='pasteAction' action='pasteAction'/><menuitem name='cutAction' action='cutAction'/><separator/><menuitem name='undoAction' action='undoAction'/><menuitem name='redoAction' action='redoAction'/><separator/><menuitem name='selectAllAction' action='selectAllAction'/><separator/><menuitem name='indentAction' action='indentAction'/><menuitem name='unindentAction' action='unindentAction'/><separator/><menuitem name='CommentRegionAction' action='CommentRegionAction'/><menuitem name='UncommentRegionAction' action='UncommentRegionAction'/><menuitem name='Action' action='Action'/></menu><menu name='ShellAction' action='ShellAction'><menu name='LanguageAction' action='LanguageAction'><menuitem name='PythonAction' action='PythonAction'/><menuitem name='RubyAction' action='RubyAction'/><menuitem name='SchemeAction' action='SchemeAction'/><menuitem name='JigsawAction' action='JigsawAction'/></menu></menu><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='yesAction' action='yesAction'/><toolitem name='stopAction' action='stopAction'/><toolitem name='goForwardAction' action='goForwardAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vpaned2 = new global::Gtk.VPaned ();
		this.vpaned2.CanFocus = true;
		this.vpaned2.Name = "vpaned2";
		this.vpaned2.Position = 307;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.notebook_docs = new global::Gtk.Notebook ();
		this.notebook_docs.CanFocus = true;
		this.notebook_docs.Name = "notebook_docs";
		this.notebook_docs.CurrentPage = 0;
		// Container child notebook_docs.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		// Container child button4.Gtk.Container+ContainerChild
		global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w5 = new global::Gtk.HBox ();
		w5.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-help", global::Gtk.IconSize.LargeToolbar);
		w5.Add (w6);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w8 = new global::Gtk.Label ();
		w8.LabelProp = global::Mono.Unix.Catalog.GetString ("Getting started...");
		w8.UseUnderline = true;
		w5.Add (w8);
		w4.Add (w5);
		this.button4.Add (w4);
		this.vbuttonbox1.Add (this.button4);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button4]));
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		// Container child button3.Gtk.Container+ContainerChild
		global::Gtk.Alignment w13 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w14 = new global::Gtk.HBox ();
		w14.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w15 = new global::Gtk.Image ();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.LargeToolbar);
		w14.Add (w15);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w17 = new global::Gtk.Label ();
		w17.LabelProp = global::Mono.Unix.Catalog.GetString ("New script");
		w17.UseUnderline = true;
		w14.Add (w17);
		w13.Add (w14);
		this.button3.Add (w13);
		this.vbuttonbox1.Add (this.button3);
		global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button3]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		// Container child button2.Gtk.Container+ContainerChild
		global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w23 = new global::Gtk.HBox ();
		w23.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w24 = new global::Gtk.Image ();
		w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.LargeToolbar);
		w23.Add (w24);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w26 = new global::Gtk.Label ();
		w26.LabelProp = global::Mono.Unix.Catalog.GetString ("Open...");
		w26.UseUnderline = true;
		w23.Add (w26);
		w22.Add (w23);
		this.button2.Add (w22);
		this.vbuttonbox1.Add (this.button2);
		global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button2]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.hbox1.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image69 = new global::Gtk.Image ();
		this.image69.Name = "image69";
		this.image69.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "abstract-butterfly-sm.gif"));
		this.hbox1.Add (this.image69);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image69]));
		w32.Position = 1;
		this.notebook_docs.Add (this.hbox1);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Home");
		this.notebook_docs.SetTabLabel (this.hbox1, this.label2);
		this.label2.ShowAll ();
		// Container child notebook_docs.Gtk.Notebook+NotebookChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.prompt = new global::Gtk.Label ();
		this.prompt.Name = "prompt";
		this.prompt.LabelProp = global::Mono.Unix.Catalog.GetString ("python>");
		this.prompt.Justify = ((global::Gtk.Justification)(1));
		this.vbox3.Add (this.prompt);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.prompt]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button ();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		// Container child button10.Gtk.Container+ContainerChild
		global::Gtk.Alignment w35 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w36 = new global::Gtk.HBox ();
		w36.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w37 = new global::Gtk.Image ();
		w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
		w36.Add (w37);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w39 = new global::Gtk.Label ();
		w36.Add (w39);
		w35.Add (w36);
		this.button10.Add (w35);
		this.hbox3.Add (this.button10);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button10]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button ();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		// Container child button11.Gtk.Container+ContainerChild
		global::Gtk.Alignment w44 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w45 = new global::Gtk.HBox ();
		w45.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w46 = new global::Gtk.Image ();
		w46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
		w45.Add (w46);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w48 = new global::Gtk.Label ();
		w45.Add (w48);
		w44.Add (w45);
		this.button11.Add (w44);
		this.hbox3.Add (this.button11);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button11]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w53.Position = 1;
		w53.Expand = false;
		w53.Fill = false;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		this.hbox2.Add (this.vbox2);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.hbox2.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.scrolledwindow1]));
		w56.Position = 1;
		this.notebook_docs.Add (this.hbox2);
		global::Gtk.Notebook.NotebookChild w57 = ((global::Gtk.Notebook.NotebookChild)(this.notebook_docs[this.hbox2]));
		w57.Position = 1;
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Shell");
		this.notebook_docs.SetTabLabel (this.hbox2, this.label1);
		this.label1.ShowAll ();
		this.vpaned2.Add (this.notebook_docs);
		global::Gtk.Paned.PanedChild w58 = ((global::Gtk.Paned.PanedChild)(this.vpaned2[this.notebook_docs]));
		w58.Resize = false;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.notebook_tools = new global::Gtk.Notebook ();
		this.notebook_tools.CanFocus = true;
		this.notebook_tools.Name = "notebook_tools";
		this.notebook_tools.CurrentPage = 0;
		this.notebook_tools.Scrollable = true;
		// Container child notebook_tools.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.Buffer.Text = "The Calico Project, Version 2.0.0";
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.textview1);
		this.notebook_tools.Add (this.GtkScrolledWindow);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Output");
		this.notebook_tools.SetTabLabel (this.GtkScrolledWindow, this.label3);
		this.label3.ShowAll ();
		this.vpaned2.Add (this.notebook_tools);
		this.vbox1.Add (this.vpaned2);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vpaned2]));
		w62.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Language:");
		this.statusbar1.Add (this.label4);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label4]));
		w63.Position = 0;
		w63.Expand = false;
		w63.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Python</i>");
		this.label5.UseMarkup = true;
		this.statusbar1.Add (this.label5);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label5]));
		w64.Position = 1;
		w64.Expand = false;
		w64.Fill = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w65.Position = 3;
		w65.Expand = false;
		w65.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 558;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction1.Activated += new global::System.EventHandler (this.OnNewAction1Activated);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.openAction1.Activated += new global::System.EventHandler (this.OnOpenAction1Activated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.copyAction.Activated += new global::System.EventHandler (this.OnCopyActionActivated);
		this.pasteAction.Activated += new global::System.EventHandler (this.OnPasteActionActivated);
		this.cutAction.Activated += new global::System.EventHandler (this.OnCutActionActivated);
		this.undoAction.Activated += new global::System.EventHandler (this.OnUndoActionActivated);
		this.redoAction.Activated += new global::System.EventHandler (this.OnRedoActionActivated);
		this.selectAllAction.Activated += new global::System.EventHandler (this.OnSelectAllActionActivated);
		this.indentAction.Activated += new global::System.EventHandler (this.OnIndentActionActivated);
		this.unindentAction.Activated += new global::System.EventHandler (this.OnUnindentActionActivated);
		this.CommentRegionAction.Activated += new global::System.EventHandler (this.OnCommentRegionActionActivated);
		this.UncommentRegionAction.Activated += new global::System.EventHandler (this.OnUncommentRegionActionActivated);
		this.notebook_docs.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnNotebookDocsSwitchPage);
		this.button4.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButton4ButtonPressEvent);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
