;; Scheme
(using "Myro")
(Myro.init)
(define pic (Myro.takePicture))
(Myro.show pic)
(Myro.backward 1 1)
(Myro.forward 1 1)
(Myro.beep 1 440)
(for-each (lambda (pixel)
                   (let* ((rgb (Myro.getRGB pixel))
                          (gray (/ (+ (get rgb 0)
                                      (get rgb 1)
                                      (get rgb 2)) 3)))
                      (Myro.setRGB pixel gray gray gray)))
          (Myro.getPixels pic))
