(define count 0)
(define incr
    (lambda (name)
        (set! count (+ count 1))
        (printf "test ~s: ~s~%" count name)))

(incr 'using)
(using "Myro")
(incr 'init)
(Myro.init "/dev/rfcomm1")
(incr 'takePicture)
(define pic (Myro.takePicture))
(incr 'show)
(Myro.show pic)
(incr 'backward)
(Myro.backward 1 1)
(incr 'forward)
(Myro.forward 1 1)
(incr 'beep)
(Myro.beep 1 440)
(incr 'beep)
(Myro.beep 1 440 880)
(incr 'forward)
(Myro.forward .5 2)
(incr 'backward)
(Myro.backward .5 2)
(incr 'get)
(print (Myro.get "all"))
(incr 'getAll)
(print (Myro.getAll))
(incr 'getBattery)
(print (Myro.getBattery))
(incr)
(print (Myro.getBlob))
(incr)
(print (Myro.getConfig))
(incr)
(print (Myro.getData))
(incr)
(print (Myro.getIR))
(incr)
(print (Myro.getIRMessage))
(incr)
(print (Myro.getInfo))
(incr)
(print (Myro.getLight))
(incr)
(print (Myro.getLine))
(incr)
(print (Myro.getName))
(incr)
(print (Myro.getPassword))
(incr)
(print (Myro.getStall))
(incr)
(Myro.motors .5 .5)
(incr)
(Myro.move 1 1)
(incr)
(Myro.move -1 -1)
(incr)
(Myro.reboot)
(incr)
(Myro.rotate .5 1)
(incr)
(Myro.rotate -.5 1)
(incr)
(print (Myro.getData))
(incr)
(Myro.setLED "front" 1)
(incr)
(Myro.setLEDBack 1)
(incr)
(Myro.setLEDBack 0)
(incr)
(Myro.setLEDFront 1)
(incr)
(Myro.setLEDFront 0)
(incr)
(Myro.setName "Hello")
(incr)
(print (Myro.getName))
(incr)
(Myro.setName "Scribby")
(incr)
(print (Myro.getName))
(incr)
(Myro.setPassword "password")
(incr)
(Myro.setup)
(incr)
(Myro.stop)
(incr)
(define p (Myro.takePicture))
(incr)
(Myro.show p)
(incr)
(Myro.translate .5 1)
(incr)
(Myro.translate -.5 1)
(incr)
(Myro.turnLeft 1 .25)
(incr)
(Myro.turnLeft 0.5 .25)
(incr)
(Myro.turnRight 0.5 .25)
(incr)
(Myro.turnRight 1 .25)
