(define count 0)
(define incr
    (lambda (name)
        (set! count (+ count 1))
        (printf "test ~s: ~s~%" count name)))

(incr 'using)
(using "Myro")
(incr 'init)
(Myro.init)
(incr 'takePicture)
(define pic (Myro.takePicture))
(incr 'show)
(Myro.show pic)
(incr 'backward)
(Myro.backward 1 1)
(incr 'forward)
(Myro.forward 1 1)
(incr 'beep)
(Myro.beep 1 440)
(incr 'beep)
(Myro.beep 1 440 880)
(incr 'forward)
(Myro.forward .5 2)
(incr 'backward)
(Myro.backward .5 2)
(incr 'get)
(print (Myro.get "all"))
(incr 'getAll)
(print (Myro.getAll))
(incr 'getBattery)
(print (Myro.getBattery))
(incr 'getBlob)
(print (Myro.getBlob))
(incr 'getConfig)
(print (Myro.getConfig))
(incr 'getData)
(print (Myro.getData))
(incr 'getIR)
(print (Myro.getIR))
(incr 'getIRMessage)
(print (Myro.getIRMessage))
(incr 'getInfo)
(print (Myro.getInfo))
(incr 'getLight)
(print (Myro.getLight))
(incr 'getLine)
(print (Myro.getLine))
(incr 'getName)
(print (Myro.getName))
(incr 'getPassword)
(print (Myro.getPassword))
(incr 'getStall)
(print (Myro.getStall))
(incr 'motors)
(Myro.motors .5 .5)
(incr 'move)
(Myro.move 1 1)
(incr 'move)
(Myro.move -1 -1)
(incr 'reboot)
(Myro.reboot)
(incr 'rotate)
(Myro.rotate .5 1)
(incr 'rotate)
(Myro.rotate -.5 1)
(incr 'getData)
(print (Myro.getData))
(incr 'setLED)
(Myro.setLED "front" 1)
(incr 'setLEDBack)
(Myro.setLEDBack 1)
(incr 'setLEDBack)
(Myro.setLEDBack 0)
(incr 'setLEDFront)
(Myro.setLEDFront 1)
(incr 'setLEDFront)
(Myro.setLEDFront 0)
(incr 'setName)
(Myro.setName "Hello")
(incr 'getName)
(print (Myro.getName))
(incr 'setName)
(Myro.setName "Scribby")
(incr 'getName)
(print (Myro.getName))
(incr 'setPassword)
(Myro.setPassword "password")
(incr 'setup)
(Myro.setup)
(incr 'stop)
(Myro.stop)
(incr 'takePicture)
(define p (Myro.takePicture))
(incr 'show)
(Myro.show p)
(incr 'translate)
(Myro.translate .5 1)
(incr 'translate)
(Myro.translate -.5 1)
(incr 'turnLeft)
(Myro.turnLeft 1 .25)
(incr 'turnLeft)
(Myro.turnLeft 0.5 .25)
(incr 'turnRight)
(Myro.turnRight 0.5 .25)
(incr 'trunRight)
(Myro.turnRight 1 .25)
